/*
 * Copyright (c) 2026 Lyxot and contributors.
 *
 * 此源代码的使用受 GNU AFFERO GENERAL PUBLIC LICENSE version 3 许可证的约束, 可以在以下链接找到该许可证。
 * Use of this source code is governed by the GNU AGPLv3 license, which can be found at the following link.
 *
 * https://github.com/Lyxot/TimeFlow/blob/master/LICENSE
 */

CREATE TABLE users
(
    id                           integer                NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    auth_id                      uuid                   NOT NULL,
    username                     character varying(50)  NOT NULL,
    email                        character varying(255) NOT NULL,
    password_hash                character varying(255) NOT NULL,
    selected_schedule_id         smallint,
    selected_schedule_updated_at timestamp without time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_auth_id_unique UNIQUE (auth_id),
    CONSTRAINT users_email_unique UNIQUE (email)
);

CREATE TABLE refresh_tokens
(
    id         bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id    integer NOT NULL,
    jti        uuid    NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
    CONSTRAINT refresh_tokens_jti_unique UNIQUE (jti),
    CONSTRAINT fk_refresh_tokens_user_id__id
        FOREIGN KEY (user_id) REFERENCES users (id)
            ON UPDATE RESTRICT
            ON DELETE CASCADE
);

CREATE INDEX refresh_tokens_user_id ON refresh_tokens USING btree (user_id);

CREATE TABLE verification_codes
(
    id         integer                NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email      character varying(255) NOT NULL,
    code       character varying(6)   NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone NOT NULL,
    CONSTRAINT verification_codes_pkey PRIMARY KEY (id)
);

CREATE INDEX verification_codes_email ON verification_codes USING btree (email);

CREATE TABLE schedules
(
    id                      bigint                 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id                 integer                NOT NULL,
    local_id                smallint               NOT NULL,
    name                    character varying(255) NOT NULL,
    term_start_date         date                   NOT NULL,
    term_end_date           date                   NOT NULL,
    display_weekends        boolean                NOT NULL,
    lesson_time_period_info jsonb                  NOT NULL,
    deleted                 boolean                NOT NULL DEFAULT false,
    created_at              timestamp without time zone NOT NULL,
    updated_at              timestamp without time zone NOT NULL,
    CONSTRAINT schedules_pkey PRIMARY KEY (id),
    CONSTRAINT schedules_user_id_local_id_unique UNIQUE (user_id, local_id),
    CONSTRAINT fk_schedules_user_id__id
        FOREIGN KEY (user_id) REFERENCES users (id)
            ON UPDATE RESTRICT
            ON DELETE CASCADE
);

CREATE INDEX schedules_user_id ON schedules USING btree (user_id);
CREATE INDEX schedules_local_id ON schedules USING btree (local_id);

CREATE TABLE courses
(
    id          bigint                 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    schedule_id bigint                 NOT NULL,
    local_id    smallint               NOT NULL,
    name        character varying(255) NOT NULL,
    teacher     character varying(128),
    classroom   character varying(128),
    time        jsonb                  NOT NULL,
    weekday     integer                NOT NULL,
    color       integer                NOT NULL,
    weeks       integer[] NOT NULL,
    note        character varying(1000),
    CONSTRAINT courses_pkey PRIMARY KEY (id),
    CONSTRAINT courses_schedule_id_local_id_unique UNIQUE (schedule_id, local_id),
    CONSTRAINT fk_courses_schedule_id__id
        FOREIGN KEY (schedule_id) REFERENCES schedules (id)
            ON UPDATE RESTRICT
            ON DELETE CASCADE
);

CREATE INDEX courses_schedule_id ON courses USING btree (schedule_id);
CREATE INDEX courses_local_id ON courses USING btree (local_id);
