openapi: 3.0.3
info:
  title: TimeFlow API
  description: The RESTful API for the TimeFlow application, supporting cloud sync and data management.
  version: 1.2.0

servers:
  - url: /api/v1
    description: API Version 1

# Reusable components
components:
  # Security scheme for protected endpoints
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  # Data models (schemas)
  schemas:
    # Primitive Types
    Error:
      type: object
      properties:
        message:
          type: string
          description: A human-readable error message.
    PingResponse:
      type: object
      properties:
        status: { type: string, example: "ok" }
    VersionResponse:
      type: object
      properties:
        version: { type: string, description: "Application version" }
        buildTime: { type: string, description: "The timestamp when the application was built" }
    Date:
      type: object
      properties:
        year: { type: integer, format: int32 }
        month: { type: integer, format: int32 }
        day: { type: integer, format: int32 }
    Time:
      type: object
      properties:
        hour: { type: integer, format: int32 }
        minute: { type: integer, format: int32 }
    Range:
      type: object
      properties:
        start: { type: integer, format: int32 }
        end: { type: integer, format: int32 }
    WeekList:
      type: object
      properties:
        weeks:
          type: array
          items: { type: integer, format: int32 }
    Weekday:
      type: string
      enum: [ MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY ]
    ThemeMode:
      type: string
      enum: [ SYSTEM, LIGHT, DARK ]
    Lesson:
      type: object
      properties:
        start: { $ref: '#/components/schemas/Time' }
        end: { $ref: '#/components/schemas/Time' }
    LessonTimePeriodInfo:
      type: object
      properties:
        morning: { type: array, items: { $ref: '#/components/schemas/Lesson' } }
        afternoon: { type: array, items: { $ref: '#/components/schemas/Lesson' } }
        evening: { type: array, items: { $ref: '#/components/schemas/Lesson' } }

    # Core Data Models
    Course:
      type: object
      properties:
        name: { type: string }
        teacher: { type: string }
        classroom: { type: string }
        time: { $ref: '#/components/schemas/Range' }
        weekday: { $ref: '#/components/schemas/Weekday' }
        week: { $ref: '#/components/schemas/WeekList' }
        color: { type: integer, format: int32 }
        note: { type: string }
    CourseSummary:
      type: object
      properties:
        name: { type: string }
        classroom: { type: string }
        teacher: { type: string }
    Schedule:
      type: object
      properties:
        id: { type: integer, description: "The unique ID of the schedule." }
        name: { type: string }
        deleted: { type: boolean }
        courses:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Course'
        termStartDate: { $ref: '#/components/schemas/Date' }
        termEndDate: { $ref: '#/components/schemas/Date' }
        lessonTimePeriodInfo: { $ref: '#/components/schemas/LessonTimePeriodInfo' }
        displayWeekends: { type: boolean }
    ScheduleSummary:
      type: object
      properties:
        id: { type: integer, description: "The unique ID of the schedule." }
        name: { type: string }
        deleted: { type: boolean }
        termStartDate: { $ref: '#/components/schemas/Date' }
        termEndDate: { $ref: '#/components/schemas/Date' }
    Settings:
      type: object
      properties:
        themeMode: { $ref: '#/components/schemas/ThemeMode' }
        themeDynamicColor: { type: boolean }
        themeColor: { type: integer, format: int32 }
        schedules:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Schedule'
        selectedScheduleID: { type: integer }

    # Auth Schemas
    VerificationCodeRequest:
      type: object
      required: [ email ]
      properties:
        email: { type: string, format: email }
    UserRegistrationRequest:
      type: object
      required: [ username, email, password, code ]
      properties:
        username: { type: string }
        email: { type: string, format: email }
        password: { type: string, format: password }
        code: { type: string, description: "The 6-digit verification code sent to the user's email." }
    UserLoginRequest:
      type: object
      required: [ email, password ]
      properties:
        email: { type: string, format: email }
        password: { type: string, format: password }
    TokenResponse:
      type: object
      properties:
        accessToken: { type: string, description: "Short-lived JWT Access Token" }
        refreshToken: { type: string, description: "Long-lived JWT Refresh Token. Conditionally returned.", nullable: true }
    RefreshTokenRequest:
      type: object
      properties:
        rotate: { type: boolean, description: "If true, the server will return a new refresh token (rotation).", default: false }
    UserInfoResponse:
      type: object
      properties:
        id: { type: integer }
        authId: { type: string }
        username: { type: string }
        email: { type: string, format: email }
    CheckEmailResponse:
      type: object
      properties:
        exists: { type: boolean }

    # Sync Schemas
    SyncRequest:
      type: object
      properties:
        lastSyncTimestamp: { type: string, format: date-time }
        updates:
          type: object
          properties:
            schedules: { type: array, items: { $ref: '#/components/schemas/Schedule' } }
            settings: { $ref: '#/components/schemas/Settings' }
        deletes:
          type: object
          properties:
            schedules: { type: array, items: { type: integer } }
    SyncResponse:
      type: object
      properties:
        newSyncTimestamp: { type: string, format: date-time }
        changes:
          type: object
          properties:
            schedules: { type: array, items: { $ref: '#/components/schemas/Schedule' } }
            settings: { $ref: '#/components/schemas/Settings' }

# API Paths
paths:
  /ping:
    get:
      tags: [ Health ]
      summary: Check service status
      responses:
        '200':
          description: Service is running and healthy
          content:
            application/json: { schema: { $ref: '#/components/schemas/PingResponse' } }
  /version:
    get:
      tags: [ Health ]
      summary: Get application build information
      responses:
        '200':
          description: Build version and time information
          content:
            application/json: { schema: { $ref: '#/components/schemas/VersionResponse' } }
  # Auth Endpoints
  /auth/check-email:
    get:
      tags: [ Auth ]
      summary: Check if an email is already registered
      parameters:
        - name: email
          in: query
          required: true
          schema: { type: string, format: email }
      responses:
        '200':
          description: Returns whether the email exists
          content:
            application/json: { schema: { $ref: '#/components/schemas/CheckEmailResponse' } }
        '400': { description: Email parameter is missing or invalid }
  /auth/send-verification-code:
    post:
      tags: [ Auth ]
      summary: Send a registration verification code
      requestBody:
        required: true
        content:
          application/json: { schema: { $ref: '#/components/schemas/VerificationCodeRequest' } }
      responses:
        '202': { description: Successfully accepted the request to send an email. }
        '400': { description: The email format is invalid. }
        '409': { description: The email address is already registered. }
        '429': { description: Too many requests. Please try again later. }
  /auth/register:
    post:
      tags: [ Auth ]
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json: { schema: { $ref: '#/components/schemas/UserRegistrationRequest' } }
      responses:
        '201': { description: User created successfully }
        '400': { description: Invalid input or user already exists }
        '429': { description: Too many requests }
  /auth/login:
    post:
      tags: [ Auth ]
      summary: Log in a user
      requestBody:
        required: true
        content:
          application/json: { schema: { $ref: '#/components/schemas/UserLoginRequest' } }
      responses:
        '200':
          description: Successful login, returns access and refresh tokens
          content:
            application/json: { schema: { $ref: '#/components/schemas/TokenResponse' } }
        '401': { description: Invalid credentials }
        '429': { description: Too many requests }
  /auth/logout:
    post:
      tags: [ Auth ]
      summary: Log out and revoke refresh token
      security: [ { bearerAuth: [ ] } ]
      description: >
        Revokes the current refresh token, effectively logging out the user.
        The access token will still be valid until it expires naturally.
      responses:
        '204': { description: Successfully logged out and refresh token revoked }
        '401': { description: Unauthorized or invalid refresh token }
  /auth/refresh:
    post:
      tags: [ Auth ]
      summary: Refresh an access token
      security: [ { bearerAuth: [ ] } ]
      description: >
        Provides a new access token by validating a JWT of type 'REFRESH' sent in the Authorization header.
        The client can optionally request to rotate the refresh token as well by sending `rotate: true` in the body.
      requestBody:
        required: false
        content:
          application/json: { schema: { $ref: '#/components/schemas/RefreshTokenRequest' } }
      responses:
        '200':
          description: Successfully refreshed. The response will always contain a new `accessToken`. It will conditionally contain a new `refreshToken` if rotation was requested.
          content:
            application/json: { schema: { $ref: '#/components/schemas/TokenResponse' } }
        '401': { description: Invalid or expired refresh token }
        '429': { description: Too many requests }
  /users/me:
    get:
      tags: [ Users ]
      summary: Get current user's profile
      security: [ { bearerAuth: [ ] } ]
      responses:
        '200':
          description: User profile
          content:
            application/json: { schema: { $ref: '#/components/schemas/UserInfoResponse' } }
        '401': { description: Unauthorized }

  # Schedules Endpoints
  /schedules:
    get:
      tags: [ Schedules ]
      summary: List all schedules for the current user
      security: [ { bearerAuth: [ ] } ]
      parameters:
        - name: deleted
          in: query
          description: >
            Controls which schedules to return based on deletion status.
            If null or not provided (default), returns only non-deleted schedules.
            If true, returns only deleted schedules.
            If false, returns only non-deleted schedules.
          required: false
          schema:
            type: boolean
            nullable: true
            default: null
      responses:
        '200':
          description: A map of schedule summaries, keyed by their local IDs.
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/ScheduleSummary'
        '401': { description: Unauthorized }
  /schedules/{scheduleId}:
    parameters:
      - name: scheduleId
        in: path
        required: true
        schema: { type: integer }
    get:
      tags: [ Schedules ]
      summary: Get a single schedule by ID
      security: [ { bearerAuth: [ ] } ]
      responses:
        '200':
          description: The full schedule object
          content:
            application/json: { schema: { $ref: '#/components/schemas/Schedule' } }
        '401': { description: Unauthorized }
        '404': { description: Schedule not found }
    put:
      tags: [ Schedules ]
      summary: Create or update a schedule
      security: [ { bearerAuth: [ ] } ]
      requestBody:
        required: true
        content:
          application/json: { schema: { $ref: '#/components/schemas/Schedule' } }
      responses:
        '201': { description: Schedule created successfully. }
        '204': { description: Schedule updated successfully. }
        '401': { description: Unauthorized }
    delete:
      tags: [ Schedules ]
      summary: Delete a schedule
      security: [ { bearerAuth: [ ] } ]
      parameters:
        - name: permanent
          in: query
          description: If true, permanently delete the schedule from the database.
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '204': { description: Schedule deleted successfully }
        '401': { description: Unauthorized }
        '404': { description: Schedule not found }

  # Courses Endpoints
  /schedules/{scheduleId}/courses:
    parameters:
      - name: scheduleId
        in: path
        required: true
        schema: { type: integer }
    get:
      tags: [ Courses ]
      summary: List all course summaries for a schedule
      security: [ { bearerAuth: [ ] } ]
      responses:
        '200':
          description: A map of course summaries, keyed by their local IDs.
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/CourseSummary'
        '401': { description: Unauthorized }
        '404': { description: Schedule not found }
  /schedules/{scheduleId}/courses/{courseId}:
    parameters:
      - name: scheduleId
        in: path
        required: true
        schema: { type: integer }
      - name: courseId
        in: path
        required: true
        schema: { type: integer }
    get:
      tags: [ Courses ]
      summary: Get a single course by ID
      security: [ { bearerAuth: [ ] } ]
      responses:
        '200':
          description: The full course object
          content:
            application/json: { schema: { $ref: '#/components/schemas/Course' } }
        '401': { description: Unauthorized }
        '404': { description: Schedule or Course not found }
    put:
      tags: [ Courses ]
      summary: Create or update a specific course
      security: [ { bearerAuth: [ ] } ]
      requestBody:
        required: true
        content:
          application/json: { schema: { $ref: '#/components/schemas/Course' } }
      responses:
        '201': { description: Course created successfully. }
        '204': { description: Course updated successfully. }
        '401': { description: Unauthorized }
        '404': { description: Schedule not found }
    delete:
      tags: [ Courses ]
      summary: Delete a course from a schedule
      security: [ { bearerAuth: [ ] } ]
      responses:
        '204': { description: Course deleted successfully }
        '401': { description: Unauthorized }
        '404': { description: Schedule or Course not found }

  # Settings Endpoints
  /settings:
    get:
      tags: [ Settings ]
      summary: Get user settings
      security: [ { bearerAuth: [ ] } ]
      responses:
        '200':
          description: The user's settings object
          content:
            application/json: { schema: { $ref: '#/components/schemas/Settings' } }
        '401': { description: Unauthorized }
    put:
      tags: [ Settings ]
      summary: Update/replace user settings
      security: [ { bearerAuth: [ ] } ]
      requestBody:
        required: true
        content:
          application/json: { schema: { $ref: '#/components/schemas/Settings' } }
      responses:
        '200':
          description: Settings updated
          content:
            application/json: { schema: { $ref: '#/components/schemas/Settings' } }
        '401': { description: Unauthorized }

  # Sync Endpoint
  /sync:
    post:
      tags: [ Sync ]
      summary: Perform a sync operation
      security: [ { bearerAuth: [ ] } ]
      requestBody:
        required: true
        content:
          application/json: { schema: { $ref: '#/components/schemas/SyncRequest' } }
      responses:
        '200':
          description: Sync successful
          content:
            application/json: { schema: { $ref: '#/components/schemas/SyncResponse' } }
        '401': { description: Unauthorized }
